### ISSUE TITLE
LFS or S3 data for Travis deployments

### ISSUE THREAD

**Issue by pjsier** [EvictionLab/eviction-lab-etl#1]
@Lane so I have this up and running if you just do `make all`, but the longest part of the process is downloading all of the census data. I think there's still a value to keeping as little source data as possible in the repo, but we probably need to make a compromise here.

To make sure that just about everything is re-run and not worry too much about changing each file, we could just have the census information in Git LFS, alternatively we could have the GeoJSON in S3 and download directly from there (quicker than the Census servers and multiple files), and the last option would be leave it as is building from scratch. Technically I think it could finish from scratch in the Travis build time, but it'd take a while. 

Which option do you think makes the most sense? I'm leaning toward just having the `census` directory GeoJSON files in, and just re-running the command if we ever need to update them.

**Comment by Lane** [comment]
First of all, great job on this!  It will definitely make future updates easier.

Only issue I can see with having the census data in the repo is that if we exceed our monthly LFS bandwidth quota (1GB / month) our Travis CI builds will fail because they won't be able to get the files from LFS.  This is a problem with our current setup as well, so I purchased a 50GB increase as a temporary fix.

If it's not too much work to store them in S3 that would be better I think, then we don't have to worry about buying more bandwidth for LFS each month.  Is that easy enough to do?
